# Generated by Django 4.2.11 on 2024-03-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_data', '0002_alter_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default=(('Active', 'Active'), ('Deactivated', 'Deactivated')), max_length=8, verbose_name='Статус'),
        ),
    ]
